nome = str(input("Digite seu nome: "))
print("Nome digitado: {}.".format(nome))
print("""Analisando seu nome: ...
...""")
nome = nome.strip()
nome = nome.title()
print(nome)
print(nome.upper())
print(nome.lower())
print("Seu nome tem {} letras.".format(len(nome)))
print("Seu nome completo tem {} letras, sem contar os espaços.".format(len(nome) - nome.count(" ")))
nome = nome.split()
print("{} tem {} letras.".format(nome[0],len(nome[0])))
print("Seu nome completo tem {} termos.".format(len(nome)))
